config/routes.rb
Rails.application.routes.draw do
  match '/customers/:id' => 'tasks#create', as: 'create_task', via: :post
  # get "new_task" => 'tasks#create', :as => :new_task
  match '/tasks/complete/:id' => 'tasks#complete', as: 'complete_task', via: :get
  # match '/tasks/new' => 'tasks#new', as: 'new_task', via: :get

  resources :customers
  resources :tasks

  root to: 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :tasks, dependent: :destroy

  before_save { email.downcase! }

  validates :name, presence: true, length: { maximum: 100 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 80 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validate :phone_pass

  def set_timezone
    Time.zone = current_customer.timezone if current_customer
  end

  def phone_pass
    if phone.present? and not phone.match(/\(?[0-9]{3}\)?-[0-9]{3}-[0-9]{4}/)
      errors.add :phone, "must be in the xxx-xxx-xxxx format"
    end
  end

  def to_s
    email
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :customer
  validates :description, presence: true

  before_save :default_values

  private

  def default_values
    self.completed ||= false
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout Proc.new { |controller| controller.request.xhr? ? nil : 'application' }

  protect_from_forgery with: :exception

  def current_customer
    params[:id]
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @task = Task.new
    @customer = current_customer
    @tasks = Customer.find(@customer).tasks
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
  end

  private
    def customer_params
      params.require(:customer).permit(:name,
                             :email,
                             :phone )
    end

    def new_customer
      respond_to do |format|
        format.html
        format.js
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def complete
     @task = Task.find(current_customer)
     @task.completed = true
     @task.save
     redirect_to customer_path(Task.find(current_customer).customer_id)
  end

  def index
    @tasks = Customer.find(current_customer).tasks.order(created_at: :desc)
  end

  def show
  end

  def new
    @customer = params[:id]
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    customer = Customer.find(@task.customer_id).id

    respond_to do |format|
      if @task.save
        format.html { redirect_to customer_path(customer) }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
  end

  private

    def task_params
      params.require(:task).permit(:description, :completed, :customer_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Form for things</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@customer, html: { class: "form-horizontal", role: "form" }) do |f| %>
          <% if @customer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

              <ul>
              <% @customer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :name, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :email, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :phone, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.phone_field :phone, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :timezone, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.time_field :timezone, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit class: "btn btn-primary" %>
            </div>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Create" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div id="page-wrap">
  <div class="page-header">
    <h1>Customer List Test</h1>
    <h2>Last Updated: Wednesday, February 10, 2016</h2>
  </div>

  <div class="table-responsive">
    <table id="customer-table" class="table table-striped table-hover">
      <thead>
        <tr>
              <th id="icon"><%= link_to_modal "#form", data: {toggle: "modal", target: "#myModal"} do %><i class="fa fa-plus-circle" href="#form" data-toggle="modal"></i><% end %></th>
              <th>Name</th>
              <th>Email</th>
              <th>Phone Number</th>
              <th>Time Zone </th>
        </tr>
      </thead>

      <tbody id="customer-tbody">
        <%= content_tag_for(:tr, @customers) do |customer| %>
        <tr class="<%= cycle('even', 'odd') -%>" data-link="<%= customer_path(customer) %>">
              <td></td>
              <td class="yellow-name"><%= customer.name %></td>
              <td><%= customer.email %></td>
              <td><%= customer.phone %></td>
              <td><%= customer.timezone %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div id="overlay">
  <div id="form" class="modal hide fade" style="display: none; ">
    <div class='modal-header'>
      <h3 class="modal-title">Add New Customer</h3>
    </div>
    <div class='modal-body'>
      <table class="modal-body-content">
        <%= form_for Customer.new, url: {action: "create"}, html: {class: "form"} do |f| %>
            <tbody class="modal-form-tbody">
              <tr class="field">
                <td class="modal-td">
                  <%= f.label "Enter Name" %>
                  <%= f.text_field :name %>
                </td>
              </tr><br>
              <tr class="field">
                <td class="modal-td">
                  <%= f.label "Enter Email Address" %>
                  <%= f.email_field :email %>
                </td>
              </tr><br>
              <tr class="field">
                <td class="modal-td">
                  <%= f.label "Enter Phone Number" %>
                  <%= f.telephone_field :phone %>
                </td>
              </tr><br>
              <tr class="field">
                <td id="modal-timezone" class="modal-td">
                  <%= f.label "Select Timezone" %>
                  <%= f.time_zone_select(:timezone) %>
                </td>
              </tr><br>
             </tbody>
           </table>
          <div class="actions">
             <%= f.submit "Done" %>
          </div>
          <% end %>
      </div>
  </div>
</div>

<div id="modal-background"></div>

<script>
$("tr[data-link]").click(function() {
  window.location = $(this).data("link")
})
</script>

app/views/customers/new.html.erb
<div id="content">
  <h1>New customer</h1>

  <%= render 'form' %>

  <%= link_to 'Back', customers_path %>
</div>

app/views/customers/show.html.erb
<div class="page-header">
  <h1><%= Customer.find(@customer).name + "'s Tasks" %></h1>
  <h3><%= Customer.find(@customer).email + " | " +  Customer.find(@customer).phone %></h3>
</div>

<div id="table-tasks">
  <table class="table-two">
    <col width="50">
    <thead class="thead-tasks">
      <tr>
        <th id="icon"><%= link_to_modal "#form2", data: {toggle: "modal", target: "#myModal2"} do %><i class="fa fa-plus-circle" href="#form2" data-toggle="modal"></i><% end %></th>
        <th id="new-task">Add New Task</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <div class="table-body">
      <tbody id="tasks-list">
        <%= content_tag_for(:tr, @tasks) do |task| %>
          <td></td>
          <td class="description"><%= task.description %></td>
          <td></td>
          <td id="last-td">
            <%= link_to("/tasks/complete/#{task.id}") do %>
              <% if task.completed %>
                <button type="submit" class="completed">Complete!</button>
              <% else %>
                <button type="submit" class="mark-completed">Mark Complete</button>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tbody>
    <div>
  </table>
</div>
<div id="modal-background"></div>

<div id="form2" class="modal hide fade" style="display: none;">
  <div class='modal-header'>
    <h3 class="modal-title-tasks">Add New Task</h3>
  </div>
  <div class='modal-body'>
    <table class="modal-body-content-tasks">
      <%= form_for(@task) do |f| %>
          <tbody class="modal-form-tbody">
            <tr class="field">
              <td class="modal-td">
                <%= f.label "Enter Task Description" %>
                <%= f.text_field :description %>
              </td>
            </tr><br>
                <%= f.hidden_field :customer_id, :value => params[:id] %>
           </tbody>
         </table>
        <div class="actions">
           <%= f.submit "Done" %>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, html: { class: "modal", role: "dialog" }) do |f| %>
  <% if @task.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :completed, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :completed, class: "form-control" %>
    </div>
  </div>
  <%= f.hidden_field :customer_id, :value => @customer.id %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Tasks Form</h1>

<%= render 'show' %>